# -*- coding: utf-8 -*-
"""Deutsche Kurzbeschreibungen. Schluessel = Original-Bezeichner aus dem Programm."""

OPTIONEN = {
"--add-dir <verzeichnisse...>": "Weitere Ordner, auf die Claude zugreifen darf.",
"--agent <agent>": "Agent für diese Sitzung; überschreibt die Einstellung.",
"--agents <json>": "Eigene Agenten direkt als JSON mitgeben.",
"--allow-dangerously-skip-permissions": "Erlaubt das spätere Abschalten aller Rückfragen, ohne es sofort zu tun.",
"--allowedTools, --allowed-tools <werkzeuge...>": "Nur diese Werkzeuge zulassen, z. B. \"Bash(git *) Edit\".",
"--append-system-prompt <text>": "Text an die Systemanweisung anhängen.",
"--autocompact <auto|tokens>": "Ab welcher Füllung automatisch zusammengefasst wird (auto oder 100k–1M).",
"--ax-screen-reader": "Ausgabe für Screenreader: flacher Text, keine Rahmen, keine Animationen.",
"--bg, --background": "Sitzung im Hintergrund starten und sofort zurückkehren. Gibt die Kennung aus, die claude attach, logs, stop und rm entgegennehmen; claude agents listet sie auf. Mit --resume <sitzungs-id> läuft diese Sitzung unter derselben Kennung im Hintergrund weiter, oder es startet eine Kopie mit entsprechendem Hinweis, falls die Sitzung noch läuft.",
"--bare": "Sparmodus: ohne Hooks, Plugins, Auto-Gedächtnis und CLAUDE.md-Suche.",
"--betas <betas...>": "Beta-Kennungen an die Schnittstelle mitsenden (nur mit API-Schlüssel).",
"--brief": "Erlaubt Claude, dir während der Arbeit kurze Zwischenmeldungen zu schicken.",
"--chrome": "Claude-in-Chrome-Anbindung einschalten.",
"--cloud [beschreibung|id|url]": "Cloud-Sitzung anlegen oder an eine bestehende andocken.",
"-c, --continue": "Letzte Unterhaltung in diesem Ordner fortsetzen.",
"--dangerously-skip-permissions": "Alle Rückfragen abschalten. Nur für abgeschottete Umgebungen ohne Internet.",
"-d, --debug [filter]": "Fehlersuche einschalten, wahlweise gefiltert (z. B. \"api,hooks\").",
"--debug-file <pfad>": "Fehlerprotokoll in diese Datei schreiben.",
"--disable-slash-commands": "Alle Skills abschalten.",
"--disallowedTools, --disallowed-tools <werkzeuge...>": "Diese Werkzeuge sperren.",
"--effort <stufe>": "Denkaufwand für die Sitzung: low, medium, high, xhigh, max.",
"--environment <id>": "Cloud-Sitzung in einer selbst betriebenen Umgebung starten.",
"--exclude-dynamic-system-prompt-sections": "Rechnerabhängige Angaben aus der Systemanweisung heraushalten (bessere Zwischenspeicherung).",
"--fallback-model <modell>": "Ersatzmodell, wenn das gewählte überlastet ist.",
"--file <angaben...>": "Dateien beim Start herunterladen (file_id:zielpfad).",
"--fork-session": "Beim Fortsetzen eine neue Sitzungs-ID vergeben statt die alte weiterzuführen.",
"--forward-subagent-text": "Text und Denkschritte der Unteragenten mit durchreichen.",
"--from-pr [wert]": "Sitzung zu einem Pull Request fortsetzen (Nummer oder URL).",
"-h, --help": "Hilfe anzeigen.",
"--ide": "Beim Start automatisch mit der Entwicklungsumgebung verbinden.",
"--include-hook-events": "Hook-Ereignisse mit in den Ausgabestrom schreiben (nur mit --print).",
"--include-partial-messages": "Teilstücke der Antwort ausgeben, sobald sie eintreffen (nur mit --print).",
"--input-format <format>": "Eingabeformat: text oder stream-json (nur mit --print).",
"--json-schema <schema>": "JSON-Schema, gegen das die Antwort geprüft wird.",
"--max-budget-usd <betrag>": "Obergrenze in Dollar für die Schnittstellenaufrufe (nur mit --print).",
"--mcp-config <dateien...>": "MCP-Server aus JSON-Dateien oder -Texten laden.",
"--model <modell>": "Modell für diese Sitzung.",
"-n, --name <name>": "Anzeigename der Sitzung.",
"--no-chrome": "Chrome-Anbindung abschalten.",
"--no-session-persistence": "Sitzung nicht auf die Festplatte schreiben.",
"--output-format <format>": "Ausgabeformat: text, json oder stream-json (nur mit --print).",
"--permission-mode <modus>": "Berechtigungsmodus: acceptEdits, plan, bypassPermissions, default.",
"--permission-prompts <target>": "Wer bei --print auf Berechtigungsabfragen antwortet: \"host\" (SDK-Host bzw. --permission-prompt-tool) oder \"none\" (automatische Ablehnung; der Berechtigungsmodus entscheidet weiterhin über alles andere). Standard: host.",
"--plugin-dir <pfad>": "Plugin aus einem Ordner oder Archiv nur für diese Sitzung laden.",
"--plugin-url <url>": "Plugin-Archiv von einer Adresse laden, nur für diese Sitzung.",
"-p, --print": "Antwort ausgeben und beenden — für Skripte und Pipes.",
"--prompt-suggestions [wert]": "Eingabevorschläge einschalten.",
"--remote-control [name]": "Sitzung mit Fernsteuerung starten (Handy, claude.ai).",
"--remote-control-session-name-prefix <prefix>": "Namensvorsatz für automatisch benannte Fernsteuer-Sitzungen.",
"--replay-user-messages": "Eingelesene Nutzernachrichten zur Bestätigung zurückgeben.",
"-r, --resume [wert]": "Unterhaltung per ID fortsetzen oder Auswahlliste öffnen.",
"--safe-mode": "Ohne alle Anpassungen starten: keine CLAUDE.md, Skills, Plugins, Hooks.",
"--session-id <uuid>": "Feste Sitzungs-ID vorgeben.",
"--setting-sources <quellen>": "Welche Einstellungsquellen geladen werden: user, project, local.",
"--settings <datei-oder-json>": "Zusätzliche Einstellungen aus Datei oder JSON-Text.",
"--strict-mcp-config": "Nur die per --mcp-config angegebenen MCP-Server verwenden.",
"--system-prompt <text>": "Systemanweisung für die Sitzung ersetzen.",
"--system-prompt-snapshot <on|off>": "Systemanweisung einmal je Unterhaltung festhalten und danach bei jeder Anfrage sowie beim Fortsetzen unverändert wiederverwenden (empfohlen: on). Standardmäßig an für die eingebaute Anweisung; --system-prompt oder --append-system-prompt schaltet automatisch ab, damit der übergebene Text bei jedem Start frisch gilt.",
"--teleport [sitzung]": "Teleport-Sitzung fortsetzen.",
"--tmux": "tmux-Sitzung für den Arbeitsbaum anlegen (zusammen mit --worktree).",
"--tools <werkzeuge...>": "Auswahl aus den eingebauten Werkzeugen festlegen.",
"--verbose": "Ausführliche Ausgabe, unabhängig von der Einstellung.",
"-v, --version": "Versionsnummer ausgeben.",
"-w, --worktree [name]": "Neuen Git-Arbeitsbaum für diese Sitzung anlegen.",
}

UNTERBEFEHLE = {
"agents": "Hintergrund-Agenten verwalten.",
"attach": "Eine Hintergrundsitzung in diesem Terminal öffnen.",
"auth": "Anmeldung verwalten.",
"auth login": "Am Anthropic-Konto anmelden.",
"auth logout": "Abmelden.",
"auth status": "Anmeldestatus anzeigen.",
"auto-mode": "Einstellungen des automatischen Modus ansehen oder zurücksetzen.",
"auto-mode config": "Wirksame Konfiguration als JSON ausgeben.",
"auto-mode critique": "Rückmeldung zu eigenen Regeln einholen.",
"auto-mode defaults": "Mitgelieferte Standardregeln ausgeben.",
"auto-mode reset": "Auf die Standardregeln zurücksetzen.",
"doctor": "Installation prüfen. Für die große Untersuchung /doctor in einer Sitzung.",
"gateway": "Firmen-Gateway für Anmeldung und Telemetrie betreiben.",
"import": "Konfiguration eines anderen KI-Werkzeugs übernehmen.",
"install": "Native Fassung installieren (stable, latest oder feste Version).",
"logs": "Letzte Terminalausgabe einer Hintergrundsitzung anzeigen.",
"mcp": "MCP-Server einrichten und verwalten.",
"mcp add": "MCP-Server hinzufügen (stdio, http oder sse).",
"mcp add-from-claude-desktop": "Server aus Claude Desktop übernehmen (nur Mac und WSL).",
"mcp add-json": "Server aus einem JSON-Text anlegen.",
"mcp get": "Angaben zu einem Server anzeigen.",
"mcp list": "Eingerichtete Server auflisten.",
"mcp login": "An einem Server anmelden.",
"mcp logout": "Von einem Server abmelden.",
"mcp remove": "Server entfernen.",
"mcp reset-project-choices": "Projektbezogene Zustimmungen zurücksetzen.",
"mcp serve": "Claude Code selbst als MCP-Server betreiben.",
"plugin": "Plugins verwalten.",
"plugin details": "Bestandteile eines Plugins und geschätzte Kontextkosten.",
"plugin disable": "Plugin abschalten.",
"plugin enable": "Plugin einschalten.",
"plugin eval": "Testfälle gegen ein Plugin laufen lassen und bewerten.",
"plugin init|new": "Gerüst für ein neues Plugin anlegen.",
"plugin install|i": "Plugin aus einem Marktplatz installieren.",
"plugin list": "Installierte Plugins auflisten.",
"plugin marketplace": "Marktplätze verwalten.",
"plugin prune|autoremove": "Nicht mehr benötigte Plugins entfernen.",
"plugin tag": "Plugins mit Merkmalen versehen.",
"plugin uninstall|remove": "Plugin deinstallieren.",
"plugin update": "Plugin aktualisieren.",
"plugin validate": "Plugin auf Fehler prüfen.",
"project": "Projektzustand verwalten.",
"project purge": "Allen gespeicherten Zustand eines Projekts löschen.",
"respawn": "Hintergrundsitzung(en) neu starten, damit sie die aktuelle Fassung nutzen.",
"rm": "Hintergrundsitzung löschen, auch ihren Arbeitsbaum, wenn das gefahrlos möglich ist.",
"setup-token": "Langlebiges Anmeldetoken erzeugen (für Skripte und CI).",
"stop|kill": "Hintergrundsitzung anhalten; die Unterhaltung bleibt erhalten.",
"ultrareview": "Mehrstufige Code-Durchsicht in der Cloud starten.",
"update|upgrade": "Auf Aktualisierungen prüfen und installieren.",
}

# Slash-Befehle: Schluessel = Name ohne Schraegstrich
SLASH = {
"add-dir": "Weiteren Arbeitsordner hinzufügen.",
"advisor": "Claude an wichtigen Stellen ein stärkeres Modell befragen lassen.",
"agents": "Entfernt. Unteragenten liegen jetzt in .claude/agents/.",
"artifacts": "Veröffentlichte und geteilte Artefakte durchsehen.",
"auto-mode-setup": "Automatischen Modus einrichten und anpassen.",
"autocompact": "Festlegen, ab welcher Füllung automatisch zusammengefasst wird.",
"autofix-pr": "Den aktuellen Pull Request überwachen und Probleme beheben.",
"background": "Sitzung in den Hintergrund schicken und das Terminal freigeben.",
"batch": "Große Änderung planen und dann parallel ausführen lassen.",
"branch": "Die Unterhaltung an dieser Stelle verzweigen.",
"brief": "Knapp-Modus umschalten.",
"btw": "Zwischenfrage stellen, ohne den laufenden Faden zu stören.",
"bug": "Fehler melden oder die Unterhaltung teilen.",
"cd": "Die Sitzung in einen anderen Arbeitsordner umziehen.",
"chrome": "Einstellungen für Claude in Chrome öffnen.",
"claude-in-chrome": "Browser fernsteuern: klicken, tippen, Seiten auslesen.",
"clear": "Neue Sitzung mit leerem Kontext; die alte bleibt erhalten.",
"cloud-plugins": "Festlegen, ob Cloud-Sitzungen die hier eingeschalteten Plugins mitbenutzen.",
"color": "Farbe der Eingabezeile für diese Sitzung.",
"compact": "Kontext freimachen, indem das Bisherige zusammengefasst wird.",
"config": "Einstellungen öffnen.",
"context": "Kontextverbrauch als farbiges Raster anzeigen.",
"copy": "Letzte Antwort in die Zwischenablage kopieren (/copy N für ältere).",
"daemon": "Hintergrunddienste und Routinen verwalten.",
"debug": "Fehlersuche für diese Sitzung einschalten.",
"design": "Zugriff auf Design-Projekte erteilen oder entziehen.",
"design-consent": "Zugriff auf Design-Projekte erteilen.",
"design-login": "Design-Zugriff für /design-sync freischalten.",
"design-revoke": "Zugriff auf Design-Projekte entziehen.",
"design-sync": "Ein React-Designsystem nach claude.ai/design übertragen.",
"desktop": "Die laufende Sitzung in der Desktop-App weiterführen.",
"diff": "Nicht eingecheckte Änderungen und Änderungen je Zug ansehen.",
"doctor": "Installation durchleuchten und Probleme beheben.",
"effort": "Denkaufwand einstellen.",
"exit": "Sitzung beenden.",
"explain-usage": "Den eigenen Verbrauch erklären lassen.",
"export": "Unterhaltung in eine Datei oder die Zwischenablage ausgeben.",
"extra-usage": "Umbenannt in /usage-credits.",
"fast": "Schnellmodus umschalten (gleiches Modell, höheres Tempo).",
"feedback": "Rückmeldung an Anthropic senden.",
"fewer-permission-prompts": "Häufige harmlose Aufrufe erkennen und dauerhaft erlauben.",
"focus": "Nur Eingabe, Zusammenfassung und Antwort anzeigen.",
"fork": "Hintergrund-Agent starten, der die ganze Unterhaltung erbt.",
"goal": "Ein Ziel setzen, das Claude vor dem Aufhören prüft.",
"heapdump": "Speicherabbild schreiben (zur Fehlersuche).",
"help": "Hilfe und verfügbare Befehle anzeigen.",
"hooks": "Eingerichtete Hooks für Werkzeug-Ereignisse ansehen.",
"ide": "Anbindung an die Entwicklungsumgebung verwalten.",
"import": "Konfiguration eines anderen KI-Werkzeugs übernehmen.",
"init": "Eine erste CLAUDE.md aus dem vorhandenen Code erzeugen.",
"insights": "Auswertung der eigenen Sitzungen erstellen.",
"install": "Native Fassung installieren.",
"install-github-app": "Claude-GitHub-Aktionen für ein Repository einrichten.",
"install-slack-app": "Claude-App für Slack installieren.",
"keybindings": "Datei mit den Tastenkürzeln öffnen.",
"keybindings-help": "Beim Anpassen der Tastenkürzel helfen.",
"limit-reset": "Das Sitzungslimit sofort zurücksetzen und weiterarbeiten; einmal pro Woche möglich, zählt weiter aufs Wochenlimit.",
"list-agents": "Unteragenten und andere erreichbare Sitzungen auflisten.",
"logout": "Vom Anthropic-Konto abmelden.",
"login": "Am Anthropic-Konto anmelden oder Konto wechseln.",
"loop": "Einen Auftrag in festem Abstand wiederholt laufen lassen.",
"loops": "Wiederholungen auflisten, anlegen und löschen.",
"low-priority": "Nach Erreichen des Sitzungslimits mit niedrigerer Priorität fortsetzen; erneuter Aufruf stoppt das wieder.",
"mcp": "MCP-Server verwalten.",
"memory": "CLAUDE.md-Dateien und Gedächtnis-Einstellungen bearbeiten.",
"mobile": "QR-Code für die Handy-App anzeigen.",
"model": "Modell für Claude Code einstellen.",
"passes": "Eine Gratiswoche Claude Code verschenken.",
"pause-memory": "Automatisches Gedächtnis für diese Sitzung anhalten.",
"permissions": "Regeln für erlaubte und verbotene Werkzeuge verwalten.",
"plan": "Plan-Modus einschalten oder den Plan der Sitzung ansehen.",
"plan-artifact": "Den Plan als eigene Seite ablegen.",
"plugin": "Plugins verwalten.",
"plugin-types": "Zwei Typdateien schreiben: die TypeScript-Deklarationen der Plugin-Schnittstelle und die Eingaben der verbundenen MCP-Werkzeuge, zum Typisieren eines Hook-Moduls gegen diese Sitzung.",
"powerup": "Funktionen von Claude Code in kurzen Lektionen kennenlernen.",
"privacy-settings": "Datenschutz-Einstellungen ansehen und ändern.",
"pro-trial-expired": "Auswahl nach Ablauf der Pro-Testphase.",
"radio": "Lo-Fi-Radio einschalten.",
"rate-limit-options": "Möglichkeiten anzeigen, wenn das Nutzungslimit erreicht ist.",
"recap": "Einzeilige Zusammenfassung der Sitzung erzeugen.",
"release-notes": "Neuerungen der Versionen anzeigen.",
"reload-plugins": "Ausstehende Plugin-Änderungen übernehmen.",
"reload-skills": "Neu hinzugekommene oder geänderte Skills einlesen.",
"remote-control": "Sitzung vom Handy oder von claude.ai aus steuern.",
"remote-env": "Standardumgebung für Cloud-Agenten wählen.",
"rename": "Die Unterhaltung umbenennen.",
"resume": "Frühere Unterhaltung fortsetzen.",
"rewind": "Code und/oder Unterhaltung auf einen früheren Stand zurücksetzen.",
"run": "Die Anwendung starten und eine Änderung im Betrieb prüfen.",
"run-skill-generator": "Aus einem Ablauf einen neuen Skill erzeugen lassen.",
"sandbox": "Abschottung einrichten und anzeigen.",
"schedule": "Geplante Cloud-Agenten anlegen und verwalten.",
"scroll-speed": "Rollgeschwindigkeit des Mausrads einstellen.",
"session": "Adresse und QR-Code der Cloud-Sitzung anzeigen.",
"setup-bedrock": "Amazon Bedrock neu einrichten.",
"setup-cowork": "Cowork einrichten.",
"setup-vertex": "Google Vertex AI neu einrichten.",
"skill-doctor": "Zeigen, welche geladenen Skills ungenutzt Kontext kosten.",
"skills": "Verfügbare Skills auflisten.",
"status": "Zustand anzeigen: Version, Modell, Konto, Anbindung.",
"statusline": "Statuszeile einrichten.",
"stickers": "Claude-Code-Aufkleber bestellen.",
"stop": "Diese Hintergrundsitzung beenden; Protokoll und Arbeitsbaum bleiben.",
"subtask": "Unteragent mit vollem Kontext losschicken; Ergebnis kommt zurück.",
"tasks": "Alles ansehen und verwalten, was im Hintergrund läuft.",
"team-onboarding": "Anleitung für Kollegen aus der eigenen Nutzung erzeugen.",
"teleport": "Eine Sitzung von claude.ai hier fortsetzen.",
"terminal-setup": "Tastenbelegung des Terminals einrichten (Zeilenumbruch).",
"theme": "Farbschema wechseln.",
"tui": "Oberflächenart wählen: normal oder bildschirmfüllend.",
"ultraplan": "Einen bearbeitbaren Plan im Web entwerfen lassen.",
"ultrareview": "Mehrstufige Fehlersuche im Zweig, in der Cloud.",
"update": "Auf die neueste Fassung wechseln.",
"update-config": "Einstellungen und Hooks in settings.json anpassen.",
"upgrade": "Auf Max wechseln für höhere Grenzen und mehr Opus.",
"usage": "Kosten der Sitzung, Verbrauch und Aktivität anzeigen.",
"usage-credits": "Guthaben einrichten oder beim Administrator anfragen.",
"version": "Version dieser Sitzung anzeigen.",
"voice": "Sprachmodus umschalten.",
"web-setup": "Claude Code im Web mit dem GitHub-Konto verbinden.",
"wellbeing": "Pausenerinnerungen und Ruhezeiten einstellen.",
"workflow-launch-exec": "Vom Server angestoßenen Arbeitsablauf ausführen.",
"workflows": "Laufende und abgeschlossene Arbeitsabläufe durchsehen.",
"claude-api": "Nachschlagewerk zur Claude-Schnittstelle (Modelle, Preise, Werkzeuge).",
"code-review": "Änderungen auf Fehler und Vereinfachungen durchsehen.",
"dataviz": "Diagramme und Auswertungsseiten sauber gestalten.",
"security-review": "Die Änderungen im Zweig auf Sicherheitsprobleme prüfen.",
"simplify": "Geänderten Code aufräumen und vereinfachen.",
"artifact-design": "Gestaltungsregeln für veröffentlichte Seiten.",
"artifact-diagramming": "Diagramme für veröffentlichte Seiten.",
"artifact-capabilities": "Was veröffentlichte Seiten zur Laufzeit können.",
"artifact-components": "Baukasten wiederverwendbarer Bausteine für veröffentlichte Seiten.",
"commit": "Legt einen Git-Commit an, mit passend geschriebener Nachricht.",
"commit-push-pr": "Committen, hochladen und einen Pull Request eröffnen – in einem Zug.",
"cowork-plugin": "Legt ein neues Cowork-Plugin an oder passt ein vorhandenes an.",
"memory-types": "Nachschlagewerk zu den Gedächtnisarten: was wohin gehört und wann.",
"prototype": "Macht aus einer Idee einen lauffähigen Entwurf und veröffentlicht ihn als Seite.",
"verify": "Prüft nach, ob eine Änderung wirklich tut, was sie soll – im echten Durchlauf.",
"whiteboard": "Öffnet eine freie Zeichenfläche für Skizzen und Schaubilder.",
"whiteboard-mp": "Öffnet ein Mehrspieler-Whiteboard: Striche und Cursor anderer Betrachter erscheinen live mit.",
"workshop": "Entwirft etwas Schritt für Schritt gemeinsam mit Dir, als wachsendes Dokument.",
}

# ------------------------------------------------------- Seitentexte ----
# Alles, was keine Befehlsbeschreibung ist: Überschriften, Kästen, Fußzeile.
# {v} = Fassung, {vorg} = Vorfassung, {datum} = Datum dieser Ausgabe,
# {vorg_datum} = Datum der Vorausgabe, {n} = eine Anzahl.
SEITE = {
"lang": "de",
"datum_kurz": "{t:02d}.{m:02d}.{j}",
"datum_lang": "{t}. {mn} {j}",
"monate": ["Januar", "Februar", "März", "April", "Mai", "Juni", "Juli",
           "August", "September", "Oktober", "November", "Dezember"],
"titel": "Claude Code · Befehlsreferenz {v}",
"kopfzeile": "Vollständige Referenz · geprüft gegen Version {v}",
"h1": "Claude Code<br>Befehlsreferenz",
"lead": "Alle Terminal-Befehle, alle Optionen und alle Slash-Befehle innerhalb einer "
        "Sitzung — mit einer Erklärung, was sie tun.",
"meta": "Zusammengestellt von Christians virtuellem Server · {datum} · "
        "Aktualisierung der Fassung vom {vorg_datum} ({vorg})",

"start_zeilen": [
    ("claude", "Startet eine Sitzung im aktuellen Ordner."),
    ("claude &quot;deine Frage&quot;", "Startet mit einer ersten Nachricht."),
    ("claude -p &quot;…&quot;", "Antwortet einmal und beendet sich — für Skripte."),
],

"kasten1_titel": "Wie diese Liste entstanden ist",
"kasten1": """
<p>Terminal-Befehle und Optionen (Teil A und B) sind direkt aus der installierten Fassung
{v} ausgelesen — <code>claude --help</code> und die Hilfe jedes Unterbefehls.</p>
<p>Die Slash-Befehle (Teil C) stammen aus den Befehlsdefinitionen im Programm selbst. Das
Ausleseverfahren erkennt auch Befehle, deren Beschreibung erst zur Laufzeit gebildet oder
aus einer Variablen geholt wird, und seit dieser Fassung ebenso solche, deren <i>Name</i>
in einer Variablen steht statt als Text im Programm. Beides kommt durch das Verdichten
des Programmcodes beim Bauen zustande und sagt nichts über den Befehl selbst aus.</p>
<p>Befehle, die im Programm angelegt, aber per Schalter abgeschaltet sind, stehen
gesondert am Ende, damit nichts als verfügbar erscheint, was es nicht ist.</p>
""",

"kasten2_titel": "Was sich seit der letzten Fassung geändert hat",

"teilA_titel": "Teil A · Terminal-Befehle und Optionen",
"teilA_unter": "Aufrufform: <code>claude [optionen] [befehl] [eingabe]</code>. "
               "Ohne Angaben startet eine Sitzung im aktuellen Ordner.",
"teilA_h3_start": "Sitzung starten",
"teilA_h3_opt": "Optionen",

"teilB_titel": "Teil B · Unterbefehle",
"teilB_unter": "Aufrufe der Form <code>claude &lt;unterbefehl&gt;</code>. "
               "Eingerückt die jeweils zugehörigen Unter-Unterbefehle.",

"teilC_titel": "Teil C · Slash-Befehle in der Sitzung",
"teilC_unter": "{n} verfügbare Befehle, alphabetisch. Grau dahinter: Zweitnamen "
               "und erwartete Argumente.",

"anhang_titel": "Anhang · Angelegt, aber abgeschaltet",
"anhang_unter": "Diese Namen existieren im Programm, sind in dieser Fassung aber per "
                "Schalter deaktiviert und stehen in einer Sitzung nicht zur Verfügung.",

"alias": "auch ",
"abgeschaltet": "im Programm angelegt, aber abgeschaltet",
"fuss": "Claude Code {v} · {opt} Optionen · {verf} verfügbare Slash-Befehle · "
        "{aus} abgeschaltet · Stand {datum}",
}
