# -*- coding: utf-8 -*-
"""English short descriptions. Keys = original identifiers from the program.

Mirror of texte_de.py. Same three dictionaries with the same keys, plus PAGE
for the surrounding page text. build_ref.py builds both languages in one run
and aborts if a key is missing on either side.
"""

OPTIONEN = {
"--add-dir <directories...>": "Additional folders Claude is allowed to touch.",
"--agent <agent>": "Agent for this session; overrides the setting.",
"--agents <json>": "Define custom agents inline as JSON.",
"--allow-dangerously-skip-permissions": "Allows turning off all prompts later, without doing so right away.",
"--allowedTools, --allowed-tools <tools...>": "Allow only these tools, e.g. \"Bash(git *) Edit\".",
"--append-system-prompt <prompt>": "Append text to the system prompt.",
"--autocompact <auto|tokens>": "When to compact automatically (auto, or 100k–1M).",
"--ax-screen-reader": "Screen-reader output: flat text, no borders, no animations.",
"--bg, --background": "Start the session in the background and return right away. Prints the id that claude attach, logs, stop and rm take; claude agents lists them. With --resume <session-id>, continues that session in the background under the same ID, or starts a copy and says so when the session is already running.",
"--bare": "Frugal mode: no hooks, plugins, auto-memory or CLAUDE.md discovery.",
"--betas <betas...>": "Send beta identifiers to the API (API key users only).",
"--brief": "Lets Claude send you short progress notes while it works.",
"--chrome": "Turn on the Claude-in-Chrome integration.",
"--cloud [description|session_id|url]": "Create a cloud session or attach to an existing one.",
"-c, --continue": "Continue the most recent conversation in this folder.",
"--dangerously-skip-permissions": "Turn off all prompts. Only for sealed-off environments without internet.",
"-d, --debug [filter]": "Turn on debugging, optionally filtered (e.g. \"api,hooks\").",
"--debug-file <path>": "Write the debug log to this file.",
"--disable-slash-commands": "Turn off all skills.",
"--disallowedTools, --disallowed-tools <tools...>": "Block these tools.",
"--effort <level>": "Thinking effort for the session: low, medium, high, xhigh, max.",
"--environment <environment_id>": "Start a cloud session in a self-hosted environment.",
"--exclude-dynamic-system-prompt-sections": "Keep machine-specific details out of the system prompt (better caching).",
"--fallback-model <model>": "Backup model for when the chosen one is overloaded.",
"--file <specs...>": "Download files at startup (file_id:target_path).",
"--fork-session": "On resume, issue a new session ID instead of continuing the old one.",
"--forward-subagent-text": "Pass through the text and thinking of subagents as well.",
"--from-pr [value]": "Resume the session belonging to a pull request (number or URL).",
"-h, --help": "Show help.",
"--ide": "Connect to the development environment automatically at startup.",
"--include-hook-events": "Write hook events into the output stream as well (only with --print).",
"--include-partial-messages": "Emit parts of the answer as they arrive (only with --print).",
"--input-format <format>": "Input format: text or stream-json (only with --print).",
"--json-schema <schema>": "JSON schema the answer is validated against.",
"--max-budget-usd <amount>": "Dollar ceiling for the API calls (only with --print).",
"--mcp-config <configs...>": "Load MCP servers from JSON files or strings.",
"--model <model>": "Model for this session.",
"-n, --name <name>": "Display name for the session.",
"--no-chrome": "Turn off the Chrome integration.",
"--no-session-persistence": "Do not write the session to disk.",
"--output-format <format>": "Output format: text, json or stream-json (only with --print).",
"--permission-mode <mode>": "Permission mode: acceptEdits, plan, bypassPermissions, default.",
"--permission-prompts <target>": "Who answers permission prompts with --print: \"host\" (the SDK host or --permission-prompt-tool) or \"none\" (auto-deny; the permission mode still decides everything else). Default: host.",
"--plugin-dir <path>": "Load a plugin from a folder or archive, for this session only.",
"--plugin-url <url>": "Load a plugin archive from a URL, for this session only.",
"-p, --print": "Print the answer and exit — for scripts and pipes.",
"--prompt-suggestions [value]": "Turn on prompt suggestions.",
"--remote-control [name]": "Start the session with Remote Control (phone, claude.ai).",
"--remote-control-session-name-prefix <prefix>": "Name prefix for auto-named Remote Control sessions.",
"--replay-user-messages": "Echo incoming user messages back for acknowledgement.",
"-r, --resume [value]": "Resume a conversation by ID, or open the picker.",
"--safe-mode": "Start without any customisation: no CLAUDE.md, skills, plugins, hooks.",
"--session-id <uuid>": "Use a fixed session ID.",
"--setting-sources <sources>": "Which setting sources to load: user, project, local.",
"--settings <file-or-json>": "Additional settings from a file or a JSON string.",
"--strict-mcp-config": "Use only the MCP servers given via --mcp-config.",
"--system-prompt <prompt>": "Replace the system prompt for the session.",
"--system-prompt-snapshot <on|off>": "Record the system prompt once per conversation and reuse it verbatim on every request and resume (recommended: on). On by default for the built-in prompt; --system-prompt or --append-system-prompt turns it off so the given text applies fresh each launch.",
"--teleport [session]": "Resume a teleport session, optionally by session ID.",
"--tmux": "Create a tmux session for the worktree (needs --worktree).",
"--tools <tools...>": "Pick the built-in tools: \"\" for none, \"default\" for all, or a list.",
"--verbose": "Override the verbose setting from the configuration.",
"-v, --version": "Show the version number.",
"-w, --worktree [name]": "Create a new git worktree for this session (name optional).",
}

UNTERBEFEHLE = {
"agents": "Manage background agents.",
"attach": "Open a background session in this terminal.",
"auth": "Manage sign-in.",
"auth login": "Sign in to the Anthropic account.",
"auth logout": "Sign out.",
"auth status": "Show sign-in status.",
"auto-mode": "View or reset the settings of automatic mode.",
"auto-mode config": "Print the effective configuration as JSON.",
"auto-mode critique": "Get feedback on your own rules.",
"auto-mode defaults": "Print the built-in default rules.",
"auto-mode reset": "Reset to the default rules.",
"doctor": "Check the installation. For the full examination use /doctor in a session.",
"gateway": "Run a company gateway for sign-in and telemetry.",
"import": "Take over the configuration of another AI tool.",
"install": "Install the native build (stable, latest or a fixed version).",
"logs": "Show a background session's recent terminal output.",
"mcp": "Set up and manage MCP servers.",
"mcp add": "Add an MCP server (stdio, http or sse).",
"mcp add-from-claude-desktop": "Import servers from Claude Desktop (Mac and WSL only).",
"mcp add-json": "Create a server from a JSON string.",
"mcp get": "Show the details of one server.",
"mcp list": "List the configured servers.",
"mcp login": "Sign in to a server.",
"mcp logout": "Sign out of a server.",
"mcp remove": "Remove a server.",
"mcp reset-project-choices": "Reset the per-project approvals.",
"mcp serve": "Run Claude Code itself as an MCP server.",
"plugin": "Manage plugins.",
"plugin details": "Contents of a plugin and its estimated context cost.",
"plugin disable": "Turn a plugin off.",
"plugin enable": "Turn a plugin on.",
"plugin eval": "Run test cases against a plugin and score them.",
"plugin init|new": "Scaffold a new plugin.",
"plugin install|i": "Install a plugin from a marketplace.",
"plugin list": "List the installed plugins.",
"plugin marketplace": "Manage marketplaces.",
"plugin prune|autoremove": "Remove plugins that are no longer needed.",
"plugin tag": "Tag plugins with attributes.",
"plugin uninstall|remove": "Uninstall a plugin.",
"plugin update": "Update a plugin.",
"plugin validate": "Check a plugin for errors.",
"project": "Manage project state.",
"project purge": "Delete all stored state of a project.",
"respawn": "Restart background sessions so they run the current version.",
"rm": "Delete a background session, and its worktree when safe.",
"setup-token": "Create a long-lived authentication token (for scripts and CI).",
"stop|kill": "Stop a background session; its conversation is kept.",
"ultrareview": "Start a multi-stage code review in the cloud.",
"update|upgrade": "Check for updates and install them.",
}

SLASH = {
"add-dir": "Add another working folder.",
"advisor": "Let a stronger model weigh in at the important moments.",
"agents": "Removed. Subagents now live in .claude/agents/.",
"artifacts": "Browse published and shared artifacts.",
"auto-mode-setup": "Set up and tune automatic mode.",
"autocompact": "Decide at which fill level the context is compacted automatically.",
"autofix-pr": "Watch the current pull request and fix what breaks.",
"background": "Send the session to the background and free up the terminal.",
"batch": "Plan a large change, then have it carried out in parallel.",
"branch": "Fork the conversation at this point.",
"brief": "Toggle brief mode.",
"btw": "Ask a side question without disturbing the current thread.",
"bug": "Report a bug or share the conversation.",
"cd": "Move the session to a different working folder.",
"chrome": "Open the settings for Claude in Chrome.",
"claude-in-chrome": "Drive the browser: click, type, read pages.",
"clear": "New session with an empty context; the old one is kept.",
"cloud-plugins": "Decide whether cloud sessions use the plugins enabled here.",
"color": "Colour of the prompt box for this session.",
"compact": "Free up context by summarising what happened so far.",
"config": "Open the settings.",
"context": "Show context usage as a coloured grid.",
"copy": "Copy the last answer to the clipboard (/copy N for older ones).",
"daemon": "Manage background services and routines.",
"debug": "Turn on debugging for this session.",
"design": "Grant or revoke access to design projects.",
"design-consent": "Grant access to design projects.",
"design-login": "Unlock design access for /design-sync.",
"design-revoke": "Revoke access to design projects.",
"design-sync": "Push a React design system to claude.ai/design.",
"desktop": "Continue the running session in the desktop app.",
"diff": "Look at uncommitted changes and changes per turn.",
"doctor": "Examine the installation and fix problems.",
"effort": "Set the thinking effort.",
"exit": "End the session.",
"explain-usage": "Have your own usage explained to you.",
"export": "Write the conversation to a file or the clipboard.",
"extra-usage": "Renamed to /usage-credits.",
"fast": "Toggle fast mode (same model, higher speed).",
"feedback": "Send feedback to Anthropic.",
"fewer-permission-prompts": "Spot frequent harmless calls and allow them for good.",
"focus": "Show only the input, the summary and the answer.",
"fork": "Start a background agent that inherits the whole conversation.",
"goal": "Set a goal Claude checks before it stops.",
"heapdump": "Write a memory dump (for troubleshooting).",
"help": "Show help and the available commands.",
"hooks": "Look at the hooks configured for tool events.",
"ide": "Manage the connection to the development environment.",
"import": "Take over the configuration of another AI tool.",
"init": "Generate a first CLAUDE.md from the existing code.",
"insights": "Build a report about your own sessions.",
"install": "Install the native build.",
"install-github-app": "Set up Claude GitHub Actions for a repository.",
"install-slack-app": "Install the Claude app for Slack.",
"keybindings": "Open the keyboard shortcuts file.",
"keybindings-help": "Help with customising the keyboard shortcuts.",
"limit-reset": "Reset your session limit now and keep working; available once a week, still counts toward the weekly limit.",
"list-agents": "List subagents and other sessions you can reach.",
"logout": "Sign out of the Anthropic account.",
"login": "Sign in to the Anthropic account or switch accounts.",
"loop": "Run a task over and over at a fixed interval.",
"loops": "List, create and delete loops.",
"low-priority": "Continue after hitting the session limit at lower priority; run again to stop.",
"mcp": "Manage MCP servers.",
"memory": "Edit CLAUDE.md files and the memory settings.",
"mobile": "Show the QR code for the phone app.",
"model": "Set the model for Claude Code.",
"passes": "Give away a free week of Claude Code.",
"pause-memory": "Pause automatic memory for this session.",
"permissions": "Manage the rules for allowed and forbidden tools.",
"plan": "Turn on plan mode or look at the session's plan.",
"plan-artifact": "Save the plan as a page of its own.",
"plugin": "Manage plugins.",
"plugin-authoring": "Helps you write and debug a plugin made of function hooks.",
"plugin-types": "Write two type files: the plugin API's TypeScript declarations and the inputs of the connected MCP tools, for typing a hooks module against this session.",
"powerup": "Get to know Claude Code's features in short lessons.",
"privacy-settings": "View and change the privacy settings.",
"pro-trial-expired": "Your options once the Pro trial has run out.",
"radio": "Turn on the lo-fi radio.",
"rate-limit-options": "Show the options once the usage limit is reached.",
"recap": "Produce a one-line summary of the session.",
"release-notes": "Show what is new in each version.",
"reload-plugins": "Apply pending plugin changes.",
"reload-skills": "Read in newly added or changed skills.",
"remote-control": "Drive the session from your phone or from claude.ai.",
"remote-env": "Choose the default environment for cloud agents.",
"rename": "Rename the conversation.",
"resume": "Continue an earlier conversation.",
"rewind": "Roll code and/or conversation back to an earlier state.",
"run": "Start the application and check a change in real operation.",
"run-skill-generator": "Turn a workflow of yours into a new skill.",
"sandbox": "Set up and inspect the sandbox.",
"schedule": "Create and manage scheduled cloud agents.",
"scroll-speed": "Set the scroll speed of the mouse wheel.",
"session": "Show the address and QR code of the cloud session.",
"setup-bedrock": "Set up Amazon Bedrock again.",
"setup-claude": "Walks you through setup: pick a role, install a matching plugin, try a skill, connect tools.",
"setup-cowork": "Set up Cowork.",
"setup-vertex": "Set up Google Vertex AI again.",
"skill-doctor": "Show which loaded skills are costing context without being used.",
"skills": "List the available skills.",
"status": "Show the state: version, model, account, connections.",
"statusline": "Set up the status line.",
"stickers": "Order Claude Code stickers.",
"stop": "End this background session; log and worktree are kept.",
"subtask": "Send off a subagent with full context; the result comes back.",
"tasks": "View and manage everything running in the background.",
"team-onboarding": "Generate a guide for colleagues out of your own usage.",
"teleport": "Continue a session from claude.ai here.",
"terminal-setup": "Set up the terminal key bindings (line break).",
"theme": "Switch the colour scheme.",
"tui": "Choose the interface style: normal or full screen.",
"ultraplan": "Have an editable plan drafted on the web.",
"ultrareview": "Multi-stage bug hunt across the branch, in the cloud.",
"update": "Move to the newest version.",
"update-config": "Adjust settings and hooks in settings.json.",
"upgrade": "Move to Max for higher limits and more Opus.",
"usage": "Show the session's cost, usage and activity.",
"usage-credits": "Set up credits or ask your administrator for them.",
"version": "Show the version of this session.",
"voice": "Toggle voice mode.",
"web-setup": "Connect Claude Code on the web with your GitHub account.",
"wellbeing": "Set up break reminders and quiet hours.",
"workflow-launch-exec": "Execute a workflow triggered by the server.",
"workflows": "Look through running and finished workflows.",
"claude-api": "Reference for the Claude API (models, prices, tools).",
"claude-code-docs": "Answer questions about Claude Code itself (commands, flags, settings, hooks, skills), checked against the installed build.",
"code-review": "Review changes for bugs and simplifications.",
"dataviz": "Design charts and analytics pages properly.",
"security-review": "Check the changes on the branch for security problems.",
"simplify": "Tidy up and simplify changed code.",
"artifact-design": "Design rules for published pages.",
"artifact-diagramming": "Diagrams for published pages.",
"artifact-capabilities": "What published pages can do at runtime.",
"artifact-components": "A kit of reusable building blocks for published pages.",
"artifact-pr-review": "Publishes the review of a pull request as a shareable page: bottom line, recommendation, judgment calls, visual explainer, blind spots.",
"commit": "Creates a git commit, with a fitting message written for it.",
"commit-push-pr": "Commit, push and open a pull request — in one go.",
"cowork-plugin": "Creates a new Cowork plugin or adapts an existing one.",
"memory-types": "Reference on the kinds of memory: what belongs where, and when.",
"prototype": "Turns an idea into a working draft and publishes it as a page.",
"verify": "Checks that a change really does what it should — in a real run.",
"whiteboard": "Opens a free drawing surface for sketches and diagrams — on your own or, where available, live together with others.",
"whiteboard-mp": "Opens a multiplayer whiteboard: other viewers' strokes and cursors appear live.",
"workshop": "Designs something with you step by step, as a growing document.",
}

# ------------------------------------------------------- Page furniture ----
# Everything that is not a command description: headings, boxes, footer.
# {v} = version, {vorg} = previous version, {datum} = date of this edition,
# {vorg_datum} = date of the previous edition, {n} = a count.
SEITE = {
"lang": "en",
"datum_kurz": "{t} {mn} {j}",
"datum_lang": "{t} {mn} {j}",
"monate": ["January", "February", "March", "April", "May", "June", "July",
           "August", "September", "October", "November", "December"],
"titel": "Claude Code · Command Reference {v}",
"kopfzeile": "Complete reference · checked against version {v}",
"h1": "Claude Code<br>Command Reference",
"lead": "Every terminal command, every option and every slash command inside a session — "
        "with an explanation of what it does.",
"meta": "Compiled by Christian's virtual server · {datum} · "
        "Update of the edition of {vorg_datum} ({vorg})",

"start_zeilen": [
    ("claude", "Starts a session in the current folder."),
    ("claude &quot;your question&quot;", "Starts with a first message."),
    ("claude -p &quot;…&quot;", "Answers once and exits — for scripts."),
],

"kasten1_titel": "How this list came about",
"kasten1": """
<p>Terminal commands and options (parts A and B) are read straight out of the installed
version {v} — <code>claude --help</code> and the help of every subcommand.</p>
<p>The slash commands (part C) come from the command definitions inside the program itself.
The extraction also picks up commands whose description is only assembled at runtime or
fetched from a variable, and since this edition equally those whose <i>name</i> sits in a
variable instead of being spelled out in the code. Both are artefacts of the code being
minified at build time and say nothing about the command itself.</p>
<p>Commands that exist in the program but are switched off by a flag are listed separately
at the end, so that nothing appears available that is not.</p>
""",

"kasten2_titel": "What has changed since the last edition",

"teilA_titel": "Part A · Terminal commands and options",
"teilA_unter": "Call form: <code>claude [options] [command] [input]</code>. "
               "With no arguments it starts a session in the current folder.",
"teilA_h3_start": "Starting a session",
"teilA_h3_opt": "Options",

"teilB_titel": "Part B · Subcommands",
"teilB_unter": "Calls of the form <code>claude &lt;subcommand&gt;</code>. "
               "Indented below each one, its own subcommands.",

"teilC_titel": "Part C · Slash commands inside a session",
"teilC_unter": "{n} available commands, in alphabetical order. In grey behind them: "
               "second names and expected arguments.",

"anhang_titel": "Appendix · Present, but switched off",
"anhang_unter": "These names exist in the program, but are disabled by a flag in this "
                "version and are not available inside a session.",

"alias": "also ",
"abgeschaltet": "present in the program, but switched off",
"fuss": "Claude Code {v} · {opt} options · {verf} available slash commands · "
        "{aus} switched off · as of {datum}",
}
